[project]
name = "ComfyUI-PromptCraft"
description = "All-in-one enhancement plugin with Checkpoint & LoRA Stack and Prompt Enhancement nodes. Customizable multi-dimension tag library, anime-gen specialized. LoRA groups with inline trigger words — pick tags, 1-click quality output. LLM smart prompt expansion, no more prompt block.一个ComfyUI 全链路增强插件，包含底模&Lora栈与Prompt增强节点，内置可自定义的全维度标签库，二次元出图特化，LoRA 群组管理支持触发词内嵌，挑选标签一键优质出图，LLM 智能扩写摆脱词荒"
version = "1.3.5"
# 只支持语义化版本，不要有带后缀（MOD等）的更改
license = "GPL-2.0"
# classifiers = [
#     # For OS-independent nodes (works on all operating systems)
#     "Operating System :: OS Independent",
#
#     # OR for OS-specific nodes, specify the supported systems:
#     "Operating System :: Microsoft :: Windows",  # Windows specific
#     "Operating System :: POSIX :: Linux",  # Linux specific
#     "Operating System :: MacOS",  # macOS specific
#
#     # GPU Accelerator support. Pick the ones that are supported by your extension.
#     "Environment :: GPU :: NVIDIA CUDA",    # NVIDIA CUDA support
#     "Environment :: GPU :: AMD ROCm",       # AMD ROCm support
#     "Environment :: GPU :: Intel Arc",      # Intel Arc support
#     "Environment :: NPU :: Huawei Ascend",  # Huawei Ascend support
#     "Environment :: GPU :: Apple Metal",    # Apple Metal support
# ]


[project.urls]
Repository = "https://github.com/moton16/ComfyUI-PromptCraft"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/moton16/ComfyUI-PromptCraft/wiki"
"Bug Tracker" = "https://github.com/moton16/ComfyUI-PromptCraft/issues"

[tool.comfy]
PublisherId = "moton"
DisplayName = "ComfyUI-PromptCraft"
Icon = ""
includes = [] 
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility

